### ISSUE TITLE
i get some error in ssgOptions

### ISSUE THREAD

**Issue by zcyc** [widcardw/vue-tsx-starter#1]
![image](https://user-images.githubusercontent.com/9925064/195882351-0f06d7dc-dd65-4ac1-840b-8a7acc15c2a5.png)

error in vite.config.ts line 45-49

**Comment by widcardw** [comment]
I also have this problem😭

In vscode, it may raise errors here, and code hinting does not work, but it does not matter when building.

However, when I use sublime text, the error disappears. Maybe I should add options to tsconfig or any other files?

**Comment by zcyc** [comment]
I cant find ssgOptions in defineConfig of vite's index.d.ts exactly.
I find an issue about it in vite-ssg repo:
https://github.com/antfu/vite-ssg/issues/279#issuecomment-1212915155
But i dont know how to fix it use this way.

**Comment by widcardw** [comment]
Maybe you can just append the comment at the front of `vite.config.ts`

```ts
/// <reference types="vite-ssg" />
```

I'll have a look and try to fix it tomorrow. Thanks for raising this issue!

**Comment by zcyc** [comment]
i make a pr with #2 to fix it.
